application: 2cloudapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /connected
  script: devlinks.py
- url: /stats/.*
  script: devlinks.py
- url: /_ah/prospective_search
  script: devlinks.py
- url: /.*
  script: devlinks.py
