application: android2cloud
version: 1
runtime: python
api_version: 1


builtins:
- appstats: on

handlers:
- url: /static
  static_dir: static
- url: /connected
  script: devlinks.py
- url: /.*
  script: devlinks.py