application: 2cloudapp
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

error_handlers:
- file: default_error.html

- error_code: over_quota
  file: hard_quota.html

handlers:
- url: /js
  static_dir: js
- url: /connected
  script: devlinks.py
- url: /stats/.*
  script: devlinks.py
  login: admin
- url: /_ah/prospective_search
  script: devlinks.py
  login: admin
- url: /quota/set
  script: devlinks.py
  login: admin
- url: /.*
  script: devlinks.py
