application: 2cloudapp
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /js
  static_dir: js
- url: /connected
  script: devlinks.py
- url: /stats/.*
  script: devlinks.py
  login: admin
- url: /_ah/prospective_search
  script: devlinks.py
  login: admin
- url: /.*
  script: devlinks.py
