application: 2cloudapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /connected
  script: devlinks.py
- url: /stats/.*
  script: devlinks.py
  login: admin
- url: /_ah/prospective_search
  script: devlinks.py
  login: admin
- url: /.*
  script: devlinks.py
